Create Constructors for Mat2 class
rachmiroff/vmath pull request #34
Opened 2022-11-19 15:31 UTC by kalysbek-z

Created the constructors for Mat2 class following the design notes

Closes #14

2022-11-19 16:33 UTC, rachmiroff requested changes
* Rename `creates_new_zero_matrix` to `creates_new_identity_matrix`.
* Ensure that 4 spaces are used to indent code (like in `Vec` classes) instead of 2.

2022-11-19 16:47 UTC, rachmiroff approved these changes
LGTM!

2022-11-19 16:47 UTC, toksaitov approved these changes

2022-11-19 16:48 UTC, merged

2022-11-23 18:28 UTC, rachmiroff commented
After a more careful review, I have found the following major problems:

* The `m` array should be `final`. We were planning to create an immutable data type.
* The identity matrix does not have `1.0f` on the diagonal.
* `fails_to_creates_new...` should be `fails_to_create_new...`.
* There is unnecessary punctuation (parentheses) in the `(i * 2) + j` expression in method `get(...)`.
* You have inconsistent style putting brackets `[]` in array variable declarations. In the `Mat2` you put `[]` after the type `float`. In the test file `Mat2Test`, you put `[]` after the variable name `arr`.

No further actions are required. These are minor issues that I have pushed to `dev` on my own.