Create Constructors for Mat3 class
rachmiroff/vmath pull request #35
Opened 2022-11-19 17:42 UTC by sultanaliev-s

Created the constructors for Mat3 class following the design notes
Also implemented the get() method because I needed to test the constructors

Closes #15

2022-11-21 14:52 UTC, rachmiroff requested changes
* Would it be possible to replace the loop on line 36 in `Mat3` with the `clone()` call if possible (usually, it will use `memcpy`, which is heavily optimized).

2022-11-21 18:50 UTC, rachmiroff approved these changes
LGTM!

2022-11-21 18:50 UTC, toksaitov approved these changes

2022-11-21 18:51 UTC, merged

2022-11-23 18:32 UTC, rachmiroff commented
After a more careful review, I have found the following problems:

* The `m` array should be `final`. We were planning to create an immutable data type.
* The identity matrix does not have `1.0f` on the diagonal.
* You have inconsistent style putting brackets `[]` in array variable declarations. In the `Mat3` you put `[]` after the type `float`. In the test file `Mat3Test`, you put `[]` after the variable name `null_array`.

No further actions are required. These are minor issues that I have pushed to `dev` on my own.